Import the libraries

In [22]:
import numpy as np
import pandas as pd

From the gathering of data we manage to get the following result

In [23]:
entrance_period = [25, 35, 50, 20, 25, 35, 45, 30, 50]
name = ['Orange',
        'Noodle',
        'BadRes',
        'FriedChicken',
        'RatArissara',
        'Eurobane',
        'NewRes',
        'RicePotatoChicken',
        'Waffle']
maxx = [70, 180, 240, 90, 60, 180, 50, 60, 60]
minn = [25, 45, 30, 35, 25, 45, 30, 25, 10]
mode = [35, 120, 120, 40, 30, 120, 35, 30, 40]

df0 = pd.DataFrame(
    {
    "Name":name,
    "Min": minn,
    "Max": maxx,
    "Mode":mode,
    "Period":entrance_period
    },
    index = [i for i in range(2,11)]
)

df0

Name  Min  Max  Mode  Period
2              Orange   25   70    35      25
3              Noodle   45  180   120      35
4              BadRes   30  240   120      50
5        FriedChicken   35   90    40      20
6         RatArissara   25   60    30      25
7            Eurobane   45  180   120      35
8              NewRes   30   50    35      45
9   RicePotatoChicken   25   60    30      30
10             Waffle   10   60    40      50

Now, Let's calculate the probability for a customer to go queue up at a given restuarant

In [24]:
l = np.array(entrance_period)
one = np.ones(9)

In [25]:
f = one/l
f

array([0.04      , 0.02857143, 0.02      , 0.05      , 0.04      ,
       0.02857143, 0.02222222, 0.03333333, 0.02      ])

In [26]:
sum(list(f))

0.2826984126984127

In [27]:
f = f/sum(list(f))
f

array([0.14149354, 0.10106682, 0.07074677, 0.17686693, 0.14149354,
       0.10106682, 0.07860752, 0.11791129, 0.07074677])

f is now an array of probability in whcih a restuarant is selected

Now let us find the probability of each select output module and their corresponding factor

In [28]:
f1 = f[:5]
f2 = f[5:]
print(f1,f2,sep="\n")

[0.14149354 0.10106682 0.07074677 0.17686693 0.14149354]
[0.10106682 0.07860752 0.11791129 0.07074677]


In [29]:
def normalize(array):
    s = sum(list(array))
    return array/s, s

In [30]:
f1 = normalize(f1)
f2 = normalize(f2)
print(f1,f2,sep="\n")

(array([0.224, 0.16 , 0.112, 0.28 , 0.224]), 0.6316676024705221)
(array([0.27439024, 0.21341463, 0.32012195, 0.19207317]), 0.3683323975294778)


In [31]:
l1  = [round(i,4) for i in f1[0]]
l1, sum(l1)

([0.224, 0.16, 0.112, 0.28, 0.224], 1.0)

In [32]:
l2 = [round(i,4) for i in f2[0]]
l2, sum(l2)

([0.2744, 0.2134, 0.3201, 0.1921], 1.0)

In [33]:
prob = list(f)
prob_sub = l1 + l2
factor = [f1[1]]*5 + [f2[1]]*4
factor0_9 = list(np.array(factor)*0.9)

In [34]:
df = pd.DataFrame({
    "Name":name,
    "Min": minn,
    "Max": maxx,
    "Mode":mode,
    "Prob":prob,
    "ProbSub":prob_sub,
    "InitFactor":factor,
    "ScaledFactor":factor0_9
}
,index=[i for i in range(2,11)])

In [35]:
df

Name  Min  Max  Mode      Prob  ProbSub  InitFactor  \
2              Orange   25   70    35  0.141494   0.2240    0.631668   
3              Noodle   45  180   120  0.101067   0.1600    0.631668   
4              BadRes   30  240   120  0.070747   0.1120    0.631668   
5        FriedChicken   35   90    40  0.176867   0.2800    0.631668   
6         RatArissara   25   60    30  0.141494   0.2240    0.631668   
7            Eurobane   45  180   120  0.101067   0.2744    0.368332   
8              NewRes   30   50    35  0.078608   0.2134    0.368332   
9   RicePotatoChicken   25   60    30  0.117911   0.3201    0.368332   
10             Waffle   10   60    40  0.070747   0.1921    0.368332   

    ScaledFactor  
2       0.568501  
3       0.568501  
4       0.568501  
5       0.568501  
6       0.568501  
7       0.331499  
8       0.331499  
9       0.331499  
10      0.331499

In [36]:
df.sort_index(ascending=False)

Name  Min  Max  Mode      Prob  ProbSub  InitFactor  \
10             Waffle   10   60    40  0.070747   0.1921    0.368332   
9   RicePotatoChicken   25   60    30  0.117911   0.3201    0.368332   
8              NewRes   30   50    35  0.078608   0.2134    0.368332   
7            Eurobane   45  180   120  0.101067   0.2744    0.368332   
6         RatArissara   25   60    30  0.141494   0.2240    0.631668   
5        FriedChicken   35   90    40  0.176867   0.2800    0.631668   
4              BadRes   30  240   120  0.070747   0.1120    0.631668   
3              Noodle   45  180   120  0.101067   0.1600    0.631668   
2              Orange   25   70    35  0.141494   0.2240    0.631668   

    ScaledFactor  
10      0.331499  
9       0.331499  
8       0.331499  
7       0.331499  
6       0.568501  
5       0.568501  
4       0.568501  
3       0.568501  
2       0.568501

For the drink service

In [37]:
small_in = 5
big_in = 23
tot = small_in + big_in
tot

28

In [38]:
period_sec = 10
freq_sec = 1/period_sec
freq_min = freq_sec*60
freq_min

6.0

In [39]:
prob_drink = freq_min/tot
prob_drink

0.21428571428571427

In [40]:
print(round(prob_drink,5),1-round(prob_drink,5))

0.21429 0.78571


Exiting

In [41]:
small_big = [small_in, big_in]
exit_prob = [round(i/sum(l),5) for i in small_big]
exit_prob

[0.17857, 0.82143]