Import the libraries

In [32]:
import numpy as np
import pandas as pd

From the gathering of data we manage to get the following result

In [33]:
maxx_list = [[33,34,32],[122,125,119],[122,110,120],[30,35,28],[31,32,30],[122,109,118],[30,31,39],[30,30,32],[64,60,55],[122,110,117],[30,31,39]]
minn_list = [[15,13,20],[45,45,49],[27,20,37],[10,18,18],[14,14,14],[40,52,40],[25,18,26],[15,17,16],[10,15,13],[52,38,42],[15,17,16]]
entr_list = [[20,30,25],[72,74,73],[90,88,95],[25,28,26],[20,24,28],[72,70,70],[46,44,48],[37,39,44],[51,50,54],[72,74,73],[90,88,95]]
mode = [17, 91, 92, 21, 17, 89, 26, 24, 42, 90, 27]

In [34]:
df_raw = pd.DataFrame({
    'max_day1': [11] + [i[0] for i in maxx_list],
    'max_day2': [9] + [i[1] for i in maxx_list],
    'max_day3': [10] + [i[2] for i in maxx_list],
    'min_day1': [3] + [i[0] for i in minn_list],
    'min_day2': [2] + [i[1] for i in minn_list],
    'min_day3': [4] + [i[2] for i in minn_list],
    'mode' : [3] + mode,
    'period_day1': [9] + [i[0] for i in entr_list],
    'period_day2': [8] + [i[1] for i in entr_list],
    'period_day3': [13] + [i[2] for i in entr_list]
},
index=[i for i in range(1,13)])

In [35]:
df_raw

max_day1  max_day2  max_day3  min_day1  min_day2  min_day3  mode  \
1         11         9        10         3         2         4     3   
2         33        34        32        15        13        20    17   
3        122       125       119        45        45        49    91   
4        122       110       120        27        20        37    92   
5         30        35        28        10        18        18    21   
6         31        32        30        14        14        14    17   
7        122       109       118        40        52        40    89   
8         30        31        39        25        18        26    26   
9         30        30        32        15        17        16    24   
10        64        60        55        10        15        13    42   
11       122       110       117        52        38        42    90   
12        30        31        39        15        17        16    27   

    period_day1  period_day2  period_day3  
1             9            8           13  
2            20           30           25  
3            72           74           73  
4            90           88           95  
5            25           28           26  
6            20           24           28  
7            72           70           70  
8            46           44           48  
9            37           39           44  
10           51           50           54  
11           72           74           73  
12           90           88           95

In [36]:
peak_small = [5, 4, 6]
peak_big = [23, 21, 16]
stable_small = [1, 1, 1]
stable_big = [2, 6, 4]

In [61]:
df_raw2 = pd.DataFrame({
    'peak_small':peak_small,
    'stable_small':stable_small,
    'peak_big':peak_big,
    'stable_big':stable_big
}
)

df_raw2

peak_small  stable_small  peak_big  stable_big
0           5             1        23           2
1           4             1        21           6
2           6             1        16           4

In [37]:
entrance_period = [sum(i)/len(i) for i in entr_list]
name = ['Orange',
        'Noodle',
        'BadRes',
        'FriedChicken',
        'RatArissara',
        'Eurobane',
        'NewRes',
        'RicePotatoChicken',
        'Waffle',
        'BestRes',
        'Steak']
maxx = [sum(i)/len(i) for i in maxx_list]
minn = [sum(i)/len(i) for i in minn_list]

df0 = pd.DataFrame(
    {
    "Name":name,
    "Min": minn,
    "Max": maxx,
    "Mode":mode,
    "Period":entrance_period
    },
    index = [i for i in range(2,13)]
)

df0

Name        Min         Max  Mode     Period
2              Orange  16.000000   33.000000    17  25.000000
3              Noodle  46.333333  122.000000    91  73.000000
4              BadRes  28.000000  117.333333    92  91.000000
5        FriedChicken  15.333333   31.000000    21  26.333333
6         RatArissara  14.000000   31.000000    17  24.000000
7            Eurobane  44.000000  116.333333    89  70.666667
8              NewRes  23.000000   33.333333    26  46.000000
9   RicePotatoChicken  16.000000   30.666667    24  40.000000
10             Waffle  12.666667   59.666667    42  51.666667
11            BestRes  44.000000  116.333333    90  73.000000
12              Steak  16.000000   33.333333    27  91.000000

Now, Let's calculate the probability for a customer to go queue up at a given restuarant

In [38]:
l = np.array(entrance_period)
one = np.ones(11)

In [39]:
f = one/l
f

array([0.04      , 0.01369863, 0.01098901, 0.03797468, 0.04166667,
       0.01415094, 0.02173913, 0.025     , 0.01935484, 0.01369863,
       0.01098901])

In [40]:
sum(list(f))

0.24926154500365144

In [41]:
f = f/sum(list(f))
f

array([0.16047401, 0.05495685, 0.04408627, 0.15234874, 0.16716043,
       0.05677147, 0.08721414, 0.10029626, 0.07764872, 0.05495685,
       0.04408627])

f is now an array of probability in whcih a restuarant is selected

Now let us find the probability of each select output module and their corresponding factor

In [42]:
f1 = f[:5]
f2 = f[5:9]
f3 = f[9:11]
print(f1,f2,f3,sep="\n")

[0.16047401 0.05495685 0.04408627 0.15234874 0.16716043]
[0.05677147 0.08721414 0.10029626 0.07764872]
[0.05495685 0.04408627]


In [43]:
def normalize(array):
    s = sum(list(array))
    return array/s, s

In [44]:
f1 = normalize(f1)
f2 = normalize(f2)
f3 = normalize(f3)
print(f1,f2,f3,sep="\n")

(array([0.2771446 , 0.09491253, 0.07613863, 0.26311196, 0.28869229]), 0.5790263048191147)
(array([0.17634692, 0.27090977, 0.31154623, 0.24119708]), 0.32193057512947265)
(array([0.55487805, 0.44512195]), 0.09904312005141283)


In [45]:
l1  = [round(i,4) for i in f1[0]]
l1, sum(l1)

([0.2771, 0.0949, 0.0761, 0.2631, 0.2887], 0.9999)

In [46]:
l2 = [round(i,4) for i in f2[0]]
l2, sum(l2)

([0.1763, 0.2709, 0.3115, 0.2412], 0.9998999999999999)

In [47]:
l3 = [round(i,4) for i in f3[0]]
l3, sum(l3)

([0.5549, 0.4451], 1.0)

In [48]:
prob = list(f)
prob_sub = l1 + l2 + l3
factor = [f1[1]]*5 + [f2[1]]*4 + [f3[1]]*2
factor0_9 = list(np.array(factor)*0.9)

In [49]:
df = pd.DataFrame({
    "Name":name,
    "Min": minn,
    "Max": maxx,
    "Mode":mode,
    "Prob":prob,
    "ProbSub":prob_sub,
    "InitFactor":factor,
    "ScaledFactor":factor0_9
}
,index=[i for i in range(2,13)])

In [50]:
df

Name        Min         Max  Mode      Prob  ProbSub  \
2              Orange  16.000000   33.000000    17  0.160474   0.2771   
3              Noodle  46.333333  122.000000    91  0.054957   0.0949   
4              BadRes  28.000000  117.333333    92  0.044086   0.0761   
5        FriedChicken  15.333333   31.000000    21  0.152349   0.2631   
6         RatArissara  14.000000   31.000000    17  0.167160   0.2887   
7            Eurobane  44.000000  116.333333    89  0.056771   0.1763   
8              NewRes  23.000000   33.333333    26  0.087214   0.2709   
9   RicePotatoChicken  16.000000   30.666667    24  0.100296   0.3115   
10             Waffle  12.666667   59.666667    42  0.077649   0.2412   
11            BestRes  44.000000  116.333333    90  0.054957   0.5549   
12              Steak  16.000000   33.333333    27  0.044086   0.4451   

    InitFactor  ScaledFactor  
2     0.579026      0.521124  
3     0.579026      0.521124  
4     0.579026      0.521124  
5     0.579026      0.521124  
6     0.579026      0.521124  
7     0.321931      0.289738  
8     0.321931      0.289738  
9     0.321931      0.289738  
10    0.321931      0.289738  
11    0.099043      0.089139  
12    0.099043      0.089139

In [51]:
df.loc[1] = ['Drink', 3, 10, 3, 1, 1, 1, 1] 

In [52]:
df.sort_index(ascending=False)


Name        Min         Max  Mode      Prob  ProbSub  \
12              Steak  16.000000   33.333333    27  0.044086   0.4451   
11            BestRes  44.000000  116.333333    90  0.054957   0.5549   
10             Waffle  12.666667   59.666667    42  0.077649   0.2412   
9   RicePotatoChicken  16.000000   30.666667    24  0.100296   0.3115   
8              NewRes  23.000000   33.333333    26  0.087214   0.2709   
7            Eurobane  44.000000  116.333333    89  0.056771   0.1763   
6         RatArissara  14.000000   31.000000    17  0.167160   0.2887   
5        FriedChicken  15.333333   31.000000    21  0.152349   0.2631   
4              BadRes  28.000000  117.333333    92  0.044086   0.0761   
3              Noodle  46.333333  122.000000    91  0.054957   0.0949   
2              Orange  16.000000   33.000000    17  0.160474   0.2771   
1               Drink   3.000000   10.000000     3  1.000000   1.0000   

    InitFactor  ScaledFactor  
12    0.099043      0.089139  
11    0.099043      0.089139  
10    0.321931      0.289738  
9     0.321931      0.289738  
8     0.321931      0.289738  
7     0.321931      0.289738  
6     0.579026      0.521124  
5     0.579026      0.521124  
4     0.579026      0.521124  
3     0.579026      0.521124  
2     0.579026      0.521124  
1     1.000000      1.000000

For the drink service, we calculate it by freq_drink/total_freq

In [53]:
small_in = 5
big_in = 23
tot = small_in + big_in
tot

28

In [54]:
period_sec = 10
freq_sec = 1/period_sec
freq_min = freq_sec*60
freq_min

6.0

In [55]:
prob_drink = freq_min/tot
prob_drink

0.21428571428571427

In [56]:
print(round(prob_drink,5),1-round(prob_drink,5))

0.21429 0.78571


Exiting: finding the splitting's probability at the end

In [57]:
small_big = [small_in, big_in]
exit_prob = [round(i/sum(l),5) for i in small_big]
exit_prob

[0.00817, 0.0376]

Finding the parabola's scaling constant for the statechart

In [58]:
def a(k, T):
    a = -4*k/T**2
    return a

In [59]:
print(a(5, 40))
print(a(20, 40))

-0.0125
-0.05
