In [106]:
import numpy as np
import pandas as pd

In [107]:
l = np.array([25, 35, 50, 20, 25, 35, 45, 30, 50])
one = np.ones(9)

In [108]:
f = one/l
f

array([0.04      , 0.02857143, 0.02      , 0.05      , 0.04      ,
       0.02857143, 0.02222222, 0.03333333, 0.02      ])

In [109]:
sum(list(f))

0.2826984126984127

In [110]:
f = f/sum(list(f))
f

array([0.14149354, 0.10106682, 0.07074677, 0.17686693, 0.14149354,
       0.10106682, 0.07860752, 0.11791129, 0.07074677])

f is now an array of probability in whcih a restuarant is selected

Now let us find the probability of each select output module and their corresponding factor

In [111]:
f1 = f[:5]
f2 = f[5:]
print(f1,f2,sep="\n")

[0.14149354 0.10106682 0.07074677 0.17686693 0.14149354]
[0.10106682 0.07860752 0.11791129 0.07074677]


In [112]:
def normalize(array):
    s = sum(list(array))
    return array/s, s

In [113]:
f1 = normalize(f1)
f2 = normalize(f2)
print(f1,f2,sep="\n")

(array([0.224, 0.16 , 0.112, 0.28 , 0.224]), 0.6316676024705221)
(array([0.27439024, 0.21341463, 0.32012195, 0.19207317]), 0.3683323975294778)


In [114]:
l1  = [round(i,4) for i in f1[0]]
l1, sum(l1)

([0.224, 0.16, 0.112, 0.28, 0.224], 1.0)

In [115]:
l2 = [round(i,4) for i in f2[0]]
l2, sum(l2)

([0.2744, 0.2134, 0.3201, 0.1921], 1.0)

In [116]:
name = ['Orange',
        'Noodle',
        'BadRes',
        'FriedChicken',
        'RatArissara',
        'Eurobane',
        'NewRes',
        'RicePotatoChicken',
        'Waffle']
maxx = [70, 180, 240, 90, 60, 180, 50, 60, 60]
minn = [25, 45, 30, 35, 25, 45, 30, 25, 10]
mode = [35, 120, 120, 40, 30, 120, 35, 30, 40]
prob = list(f)
prob_sub = l1 + l2
factor = [f1[1]]*5 + [f2[1]]*4
factor0_9 = list(np.array(factor)*0.9)

In [117]:
df = pd.DataFrame({
    "Name":name,
    "Max": maxx,
    "Min": minn,
    "Mode":mode,
    "Prob":prob,
    "ProbSub":prob_sub,
    "InitFactor":factor,
    "ScaledFactor":factor0_9
}
,index=[i for i in range(2,11)])

In [118]:
df

Name  Max  Min  Mode      Prob  ProbSub  InitFactor  \
2              Orange   70   25    35  0.141494   0.2240    0.631668   
3              Noodle  180   45   120  0.101067   0.1600    0.631668   
4              BadRes  240   30   120  0.070747   0.1120    0.631668   
5        FriedChicken   90   35    40  0.176867   0.2800    0.631668   
6         RatArissara   60   25    30  0.141494   0.2240    0.631668   
7            Eurobane  180   45   120  0.101067   0.2744    0.368332   
8              NewRes   50   30    35  0.078608   0.2134    0.368332   
9   RicePotatoChicken   60   25    30  0.117911   0.3201    0.368332   
10             Waffle   60   10    40  0.070747   0.1921    0.368332   

    ScaledFactor  
2       0.568501  
3       0.568501  
4       0.568501  
5       0.568501  
6       0.568501  
7       0.331499  
8       0.331499  
9       0.331499  
10      0.331499

In [119]:
df.sort_index(ascending=False)

Name  Max  Min  Mode      Prob  ProbSub  InitFactor  \
10             Waffle   60   10    40  0.070747   0.1921    0.368332   
9   RicePotatoChicken   60   25    30  0.117911   0.3201    0.368332   
8              NewRes   50   30    35  0.078608   0.2134    0.368332   
7            Eurobane  180   45   120  0.101067   0.2744    0.368332   
6         RatArissara   60   25    30  0.141494   0.2240    0.631668   
5        FriedChicken   90   35    40  0.176867   0.2800    0.631668   
4              BadRes  240   30   120  0.070747   0.1120    0.631668   
3              Noodle  180   45   120  0.101067   0.1600    0.631668   
2              Orange   70   25    35  0.141494   0.2240    0.631668   

    ScaledFactor  
10      0.331499  
9       0.331499  
8       0.331499  
7       0.331499  
6       0.568501  
5       0.568501  
4       0.568501  
3       0.568501  
2       0.568501

For the drink service

In [120]:
small_in = 5
big_in = 23
tot = small_in + big_in
tot

28

In [121]:
period_sec = 10
freq_sec = 1/period_sec
freq_min = freq_sec*60
freq_min

6.0

In [122]:
prob_drink = freq_min/tot
prob_drink

0.21428571428571427

In [123]:
print(round(prob_drink,5),1-round(prob_drink,5))

0.21429 0.78571


Exiting

In [124]:
l = [small_in, big_in]
exit_prob = [round(i/sum(l),5) for i in l]
exit_prob

[0.17857, 0.82143]